# Generated by Django 3.2.6 on 2021-08-18 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('alpha2code', models.CharField(max_length=2)),
                ('alpha3code', models.CharField(max_length=3)),
                ('capital', models.CharField(max_length=64)),
                ('population', models.IntegerField()),
                ('timezones', models.TextField(null=True)),
                ('languages', models.TextField(null=True)),
                ('borders', models.TextField(null=True)),
            ],
        ),
    ]
